
default: illustrativePlots

include ../../backgroundEstimation/common/common.make

#--------------------------------------------------------------------------

illustrativePlots: illustrativePlots.$(ExeSuf)
	./illustrativePlots.$(ExeSuf)

